pico-8 cartridge // http://www.pico-8.com
version 35
__lua__
_set_fps(60)r=rnd
cls()s=r(-1)srand(s)
for i=1,16do pal(i,r(33)-17,1)end
poke(24364,r({7,5}))
function rnd_sign()
 return mid(1,(rnd()-.5)/0)*2-1
end

::_::
?r({"\^i","\^p","\^i\^p",""})..chr(rnd(240)\1+16),r(132)-2,r(132)-1,r(8)

---- memory fuckery
--screen_mem_start=●-웃
--
--for i=0,50 do
--local amt = rnd(5)+10
--if amt >= 1 then
-- for i=0,amt*amt do
--  poke(
--      0x6000+rnd(0x2000),
--      peek(rnd(0x7fff)))
--  poke(
--      0x6000+rnd(0x2000),
--      rnd(0xff))
-- end
--end
---- glitch
-- local gr = rnd(13)+3
-- if gr >= 1 then 
--  local on=(t()*4.0)%gr<0.1
--  local gso=on and 0 or rnd(0x1fff)\1
--  local gln=on and 0x1ffe or rnd(0x1fff-gso)\16
--  for a=0x6000+gso,0x6000+gso+gln,rnd(16)\1 do
--   poke(a,peek(a+2),peek(a-1)+(rnd(3)))
--  end
-- end
-- for i=0,1000 do
--  d=rnd(8191)
--  poke(
--   screen_mem_start+d+(rnd()*rnd_sign()), -- write to this position, if the button is pressed shift by -0.5
--   @(screen_mem_start+d-64*(mid(1,(rnd()-.5)/0)*2-1)+(rnd()*rnd_sign()))  -- peek @ this position, last part is to get 1 or -1
--  )  
-- end
--end
if(r()>.98)srand(s)
goto _
__gfx__
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00700700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00077000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00077000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00700700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
__label__
mmmmmmmmmmmmmmmmmmmmmmmmnmmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmmnmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmnmmmnmmmmmmmmfmfmfmfmfmmmmmmmmmmmmmmnmnmnnmnmnmmmmmmmmmmmmmmfmfmfmfmfmmmmmmmmnmmmnmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmnmmmmmmmmmmfmmmmmfmfmmmmmmmmmmmm7mnmnm77mnmnm7mmmmmmmmmmmmfmfmmmmmfmmmmmmmmmmnmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfmmmmmfmfmmmmmmmm7mmmmmnmnmnnmnmnmmmmm7mmmmmmmmfmfmmmmmfmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
vvmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmvv
mvmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfmmmfmmmfmmmmmmmmmm7m7mnmnmnnmnmnm7m7mmmmmmmmmmfmmmfmmmfmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmvm
mvmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmvm
mvmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfmmmmmmmfmmmmmmmmmmmmmmnmmmnnmmmnmmmmmmmmmmmmmmfmmmmmmmfmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmvm
mvmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmvm
mvmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfmfmfmfmfmmmmmmmmmmmmmmnmnmmmmnmnmmmmmmmmmmmmmmfmfmfmfmfmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmvm
vvmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmvv
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmnmnnmnmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
vmvmvmvmvmvmvmvmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmvmvmvmvmvmvmvmv
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmvmvmmmvmvmvmvmhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhmvmvmvmvmmmvmvmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
vmmmmmmmmmmmvmhmhmhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhmhmhmvmmmmmmmmmmmv
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmvmmmvmvmhmhmhmhmhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhmhmhmhmhmvmvmmmvmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmvmmmmmvmmmnmhmhmhmnmnmnmnmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmnmnmnmnmhmhmhmnmmmvmmmmmvmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
vmmmmmvmvmmmnmvmhmnmnmnmnmnmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmnmnmnmnmnmhmvmnmmmvmvmmmmmv
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
vmvmvhvhvhvhvhvmmmmmnmnmnmnmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmnmnmnmnmmmmmvhvhvhvhvhvmvmv
mmmmmhhmmmmmhhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhhmmmmmhhmmmmm
mmmmmhhhhhhmnhnmmmnmnmmmmmnhnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnhnmmmmmnmnmmmnhnmhhhhhhmmmmm
mmmmmhhhhhmhhhmmmmmmmmmmmmhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhmmmmmmmmmmmmhhhmhhhhhmmmmm
mmmmmhhhhmmhnhnmmmnmnmnmnmhhnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnhhmnmnmnmnmmmnhnhmmhhhhmmmmm
mmmmmhhmmhhmhhmmmmmmmmmmmhhmhmhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhmhmhhmmmmmmmmmmmhhmhhmmhhmmmmm
mmmmmhhhhhhhnhnmmmnmnmmmmhnmhhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhhmnhmmmmnmnmmmnhnhhhhhhhmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhmhmhnfmnmmmmmmnmfnhmhmhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmnmnmnmnmnmnmnmnmnmmmmmmmmmmmmmmmmmmmmmmmmmmmfffffmmmmmmfffffmmmmmmmmmmmmmmmmmmmmmmmmmmmnmnmnmnmnmnmnmnmnmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhmhmmnfmnmmmmmmnmfnmmhmhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfmfmfmmmmmmfmfmfmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhmfmfnfmmmmmmfnfmfmhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmnmnmnmnmnmnmnmnmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmnmnmnmnmnmnmnmnmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhmhmhmmmmmmmmmmmmmmhmhmhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmnmnmnmnmmmnmnmnmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmnmnmnmmmnmnmnmnmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmnnnnnnnnnmmmmmmmmmmmmmmmmmmmmmmmhmmmmmmmmmmmmmmmmmmhmmmmmmmmmmmmmmmmmmmmmmmnnnnnnnnnmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmnnnmnmnnnmmmmmmmnmnmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmnmnmmmmmmmnnnmnmnnnmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmnnnnnmnnnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnnnmnnnnnmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmnnnnnmnnnmnmmmnmnmnmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmnmnmnmmmnmnnnmnnnnnmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmnnnnnmnnnmmmmmmmmmmmmmmmmmmmmmmmmmmhmhmhmmmmhmhmhmmmmmmmmmmmmmmmmmmmmmmmmmmnnnmnnnnnmmmmmmmmmmmmmmmmmmmmmm
mmmmmfffffffffmmmmmmmmnnmmnmnnnmmmnmnmmmnmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmnmmmnmnmmmnnnmnmmnnmmmmmmmmfffffffffmmmmm
mmmmmfffffffffmmmmmmmmnnnnnnnnnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnnnnnnnnnmmmmmmmmfffffffffmmmmm
mmmmmffmfmffffmmmmmmmmmmmmnmnmmmnmmmmmnmnmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmnmnmmmmmnmmmnmnmmmmmmmmmmmmffffmfmffmmmmm
mmmmmfmmmmmfffmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhmmmmhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfffmmmmmfmmmmm
mmmmmffmffmfffmmmmmmmmmmmmnmnmnmnmnmnmnmnmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmnmnmnmnmnmnmnmnmmmmmmmmmmmmfffmffmffmmmmm
mmmmmfffmfffffmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhhhhhhhhhmmmmmmmmmmmmmmmmmmmmmmhhhhhhhhhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfffffmfffmmmmm
mmmmmfffffffffmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhhmmmmmhhmmmmmmmmmmmmmmmmmmmmmmhhmmmmmhhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfffffffffmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhhmhhhmhhmmmmmmmmmmmmmmmmmmmmmmhhmhhhmhhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhmmmhmhhmhhhmhhmmmmmmmmmmmmmmmmmmmmmmhhmhhhmhhmhmmmhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhhmhhhmhhmmmmmmmmmmmmmmmmmmmmmmhhmhhhmhhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhmmmhhmmmmmhhmmmmmmmmmmmmmmmmmmmmmmhhmmmmmhhmmmhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhhhhhhhhhmmmmmmmmmmmmmmmmmmmmmmhhhhhhhhhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhhhhhhhhhmmmmmmmmmmmmmmmmmmmmmmhhhhhhhhhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhmmmhhmmmmmhhmmmmmmmmmmmmmmmmmmmmmmhhmmmmmhhmmmhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhhmhhhmhhmmmmmmmmmmmmmmmmmmmmmmhhmhhhmhhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhmmmhmhhmhhhmhhmmmmmmmmmmmmmmmmmmmmmmhhmhhhmhhmhmmmhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhhmhhhmhhmmmmmmmmmmmmmmmmmmmmmmhhmhhhmhhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmfffffffffmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhhmmmmmhhmmmmmmmmmmmmmmmmmmmmmmhhmmmmmhhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfffffffffmmmmm
mmmmmfffmfffffmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhhhhhhhhhmmmmmmmmmmmmmmmmmmmmmmhhhhhhhhhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfffffmfffmmmmm
mmmmmffmffmfffmmmmmmmmmmmmnmnmnmnmnmnmnmnmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmnmnmnmnmnmnmnmnmmmmmmmmmmmmfffmffmffmmmmm
mmmmmfmmmmmfffmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhmmmmhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfffmmmmmfmmmmm
mmmmmffmfmffffmmmmmmmmmmmmnmnmmmnmmmmmnmnmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmnmnmmmmmnmmmnmnmmmmmmmmmmmmffffmfmffmmmmm
mmmmmfffffffffmmmmmmmmnnnnnnnnnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnnnnnnnnnmmmmmmmmfffffffffmmmmm
mmmmmfffffffffmmmmmmmmnnmmnmnnnmmmnmnmmmnmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmnmmmnmnmmmnnnmnmmnnmmmmmmmmfffffffffmmmmm
mmmmmmmmmmmmmmmmmmmmmmnnnnnmnnnmmmmmmmmmmmmmmmmmmmmmmmmmmhmhmhmmmmhmhmhmmmmmmmmmmmmmmmmmmmmmmmmmmnnnmnnnnnmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmnnnnnmnnnmnmmmnmnmnmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmnmnmnmmmnmnnnmnnnnnmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmnnnnnmnnnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnnnmnnnnnmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmnnnmnmnnnmmmmmmmnmnmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmnmnmmmmmmmnnnmnmnnnmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmnnnnnnnnnmmmmmmmmmmmmmmmmmmmmmmmhmmmmmmmmmmmmmmmmmmhmmmmmmmmmmmmmmmmmmmmmmmnnnnnnnnnmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmnmnmnmnmmmnmnmnmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmnmnmnmmmnmnmnmnmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhmhmhmmmmmmmmmmmmmmhmhmhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmnmnmnmnmnmnmnmnmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmnmnmnmnmnmnmnmnmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhmfmfnfmmmmmmfnfmfmhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfmfmfmmmmmmfmfmfmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhmhmmnfmnmmmmmmnmfnmmhmhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmnmnmnmnmnmnmnmnmnmmmmmmmmmmmmmmmmmmmmmmmmmmmfffffmmmmmmfffffmmmmmmmmmmmmmmmmmmmmmmmmmmmnmnmnmnmnmnmnmnmnmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhmhmhnfmnmmmmmmnmfnhmhmhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmhhhhhhhnhnmmmnmnmmmmhnmhhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhhmnhmmmmnmnmmmnhnhhhhhhhmmmmm
mmmmmhhmmhhmhhmmmmmmmmmmmhhmhmhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhmhmhhmmmmmmmmmmmhhmhhmmhhmmmmm
mmmmmhhhhmmhnhnmmmnmnmnmnmhhnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnhhmnmnmnmnmmmnhnhmmhhhhmmmmm
mmmmmhhhhhmhhhmmmmmmmmmmmmhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhmmmmmmmmmmmmhhhmhhhhhmmmmm
mmmmmhhhhhhmnhnmmmnmnmmmmmnhnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnhnmmmmmnmnmmmnhnmhhhhhhmmmmm
mmmmmhhmmmmmhhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhhmmmmmhhmmmmm
vmvmvhvhvhvhvhvmmmmmnmnmnmnmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmnmnmnmnmmmmmvhvhvhvhvhvmvmv
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
vmmmmmvmvmmmnmvmhmnmnmnmnmnmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmnmnmnmnmnmhmvmnmmmvmvmmmmmv
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmvmmmmmvmmmnmhmhmhmnmnmnmnmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmnmnmnmnmhmhmhmnmmmvmmmmmvmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmvmmmvmvmhmhmhmhmhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhmhmhmhmhmvmvmmmvmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
vmmmmmmmmmmmvmhmhmhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhmhmhmvmmmmmmmmmmmv
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmvmvmmmvmvmvmvmhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhmvmvmvmvmmmvmvmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
vmvmvmvmvmvmvmvmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmvmvmvmvmvmvmvmv
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmnmnnmnmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
vvmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmvv
mvmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfmfmfmfmfmmmmmmmmmmmmmmnmnmmmmnmnmmmmmmmmmmmmmmfmfmfmfmfmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmvm
mvmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmvm
mvmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfmmmmmmmfmmmmmmmmmmmmmmnmmmnnmmmnmmmmmmmmmmmmmmfmmmmmmmfmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmvm
mvmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmvm
mvmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfmmmfmmmfmmmmmmmmmm7m7mnmnmnnmnmnm7m7mmmmmmmmmmfmmmfmmmfmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmvm
vvmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmvv
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfmmmmmfmfmmmmmmmm7mmmmmnmnmnnmnmnmmmmm7mmmmmmmmfmfmmmmmfmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmnmmmmmmmmmmfmmmmmfmfmmmmmmmmmmmm7mnmnm77mnmnm7mmmmmmmmmmmmfmfmmmmmfmmmmmmmmmmnmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmmmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmnmmmnmmmmmmmmfmfmfmfmfmmmmmmmmmmmmmmnmnmnnmnmnmmmmmmmmmmmmmmfmfmfmfmfmmmmmmmmnmmmnmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmnmmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnmmnmmmmmmmmmmmmmmmmmmmmmmmm

